# Generated by Django 4.2.5 on 2023-10-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city_koeff', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_of_km_by_time', models.FloatField(default=1)),
                ('cost_of_km_by_dist', models.FloatField(default=1)),
                ('j', models.FloatField(default=1)),
            ],
        ),
    ]
